### ISSUE TITLE
Refresh Token in User Struct

### ISSUE THREAD

**Issue by benpallen** [aerogear/aerogear-ios-sdk#151]
Why don't you put the refresh_token in the User struct?
Access and ID tokens are in there except the refresh token.

**Comment by wtrocki** [comment]
Hello. Thank you for trying our SDK. 
Idea of SDK is to hide complexity of refreshing tokens/checking expiry date etc. When using getUser funtion token will be refreshed:
https://github.com/aerogear/aerogear-ios-sdk/blob/master/modules/auth/AgsAuth.swift#L202

However if there will be use case when refresh token will be needed for end user then we can expose it. It may happen that there is bug and under some circumstances token is not refreshed properly. We will need more info to properly address this concern.

See HeaderProvider for more info.

**Comment by benpallen** [comment]
You check if the access token is expired or not in the CurrentUser method.
So, if the access token is expired, I cannot use the refresh token.
I need to use the refresh token to be able to refresh the access token when the access token is expired. I want to use the refresh token with faceid and touchid to be able to sign in the app without typing username and password and I thought I could use the refresh token to be able to do that.

**Comment by benpallen** [comment]
Sorry, I was using release 2.0.0 and you have made some changes.
