### ISSUE TITLE
Allow retrieve Keycloak user attributes from the SDK

### ISSUE THREAD

**Issue by wei-lee** [aerogear/aerogear-ios-sdk#38]
Keycloak allows setting arbitrary attributes on users as described [here](https://www.keycloak.org/docs/3.3/server_admin/topics/users/attributes.html).

We should update the SDK to retrieve these attributes from the user profile and allow developers to access them.

**Comment by wei-lee** [comment]
@wtrocki absolutely. That's why I created those issues in Github so that people can know what kind of work they can contribute. Feel free to take the issue and work on it!

**Comment by wtrocki** [comment]
Android implementation: https://github.com/aerogear/aerogear-android-sdk/pull/149
