### ISSUE TITLE
HTTP requests fail when response body is empty due to JSON parsing

### ISSUE THREAD

**Issue by aidenkeating** [aerogear/aerogear-ios-sdk#44]
### Current behaviour
Currently when a request is made using the HTTP module it is assumed to have a JSON response. This causes a request in the Auth SDK to fail when the body of the response is empty. The HTTP status code is 200 though.

### Expected behaviour
The request should succeed when the response body is empty.

## Steps to reproduce
* Run the example app
* Login using auth
* Attempt to logout

**Comment by wtrocki** [comment]
Logged issue to alamofire: https://github.com/Alamofire/Alamofire/issues/2466
Going to provide local workaround.

**Comment by wtrocki** [comment]
Done
