### ISSUE TITLE
Update the mobile config parser to parse the version as UInt not String

### ISSUE THREAD

**Issue by rachael-oregan** [aerogear/aerogear-ios-sdk#60]
## Description
Currently the Core SDK is parsing the version property of a mobile configuration as a String. See [`MobileConfig`](https://github.com/aerogear/aerogear-ios-sdk/blob/master/modules/core/config/MobileConfig.swift#L8)  This should be refactored to `UInt` because the mobile cli tool returns the mobile configuration version as an integer. 

## Steps to reproduce
Create a client in openshift and run `mobile get clientconfig <client_id> --namespace=<namespace> -o json`. Notice the version number is and integer not a String

**Comment by wtrocki** [comment]
@rachael-oregan You are hero of the day! Thanks for pointing that out.

**Comment by wtrocki** [comment]
This happened to be trivial to fix.
