### ISSUE TITLE
error running scripts/docs.sh

### ISSUE THREAD

**Issue by finp** [aerogear/aerogear-ios-sdk#98]
$ ./scripts/docs.sh 

Generating core documentation
bundler: failed to load command: jazzy (/home/pwright/.rvm/gems/ruby-2.1.2/bin/jazzy)
Pod::Informative: [!] No podspec exists at path `agscore.podspec`.
  /home/pwright/.rvm/gems/ruby-2.1.2/gems/cocoapods-core-1.5.0/lib/cocoapods-core/specification.rb:586:in `from_file'

Probably just a ruby config thing. I'm using rvm and ruby 2.1.2, what do you recommend I try

**Comment by danielpassos** [comment]
@finp It's not your fault, the `agscore.podspec` was renamed to `AGSCore.podspec`, I'm on to fix it

**Comment by danielpassos** [comment]
https://github.com/aerogear/aerogear-ios-sdk/pull/99
